## ?? ????
spring:
  application:
    name: avab-dev
  profiles:
    active: dev
springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
  use-fqn: true
---
# ?? ????
spring:
  config:
    activate:
      on-profile: local
  datasource:
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    url: ${LOCAL_DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
# S3
cloud:
  aws:
    s3:
      bucket: avab-bucket
      folder:
        profile-image: user/profileImage
        # etc
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ${REGION}
      auto: false
    stack:
      auto: false
---
# ?? ????
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
# S3
cloud:
  aws:
    s3:
      bucket: avab-bucket
      folder:
        profile-image: user/profileImage
        # etc
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ${REGION}
      auto: false
    stack:
      auto: false
---